name: supernova_lints_example
version: 1.0.0
publish_to: none

#todo move to root level?
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.0.9+1
  supernova_lints:
    path: ../
