name: supernova_lints
description: Custom lints used in Supernova.
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  custom_lint_builder: ^0.0.9+1
  analyzer: ^4.3.1
  analyzer_plugin: ^0.10.0

dev_dependencies:
  lints: ^2.0.0
