name: supernova_lints
description: Custom lints rules used in Supernova.
homepage: https://github.com/Supernova-Studio/supernova-lints
repository: https://github.com/Supernova-Studio/supernova-lints
version: 0.0.5

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  custom_lint: ^0.0.12
  custom_lint_builder: ^0.0.12
  analyzer: ^4.0.0
  analyzer_plugin: ^0.10.0

dev_dependencies:
  lints: ^2.0.0
